### ISSUE TITLE
Question: Is it possible to deploy this library to Google Cloud Functions

### ISSUE THREAD

**Issue by aytunch** [woltapp/blurhash-python#1]
Recently, this great tool is ported to [dart and Flutter](https://github.com/Solido/Flutter-BlurHash) and it is super easy to decode a blurhash. However for the encoding part we rely on server side code. I found out that  [python code can be run from a cloud function](https://cloud.google.com/functions/docs/quickstart-python#create_a_function)

I opened an [issue](https://github.com/Solido/Flutter-BlurHash/issues/3#issuecomment-589970968) in the dart package and someone made me head to the python way.

Unfortunately this will be my first time trying something like that. I see a file called `encode.c`. Having C code in the library, is this still possible to run from Google cloud functions? 

Some guidance would be great, thanks

**Comment by lautat** [comment]
Hi, I'm pleased to hear that you've found Blurhash useful!

As a disclaimer, I am not very familiar with Google Cloud Functions, but I had a quick look at the documentation, and I think I found the answer to your question.

Google Cloud Functions has a Python 3.7 runtime, which is running a recent version of Ubuntu. I assume the hardware architecture is x86-64. This library is available as a built distribution in PyPI for Linux operating systems running on x86 hardware, which means that the native extension has been compiled and a compiler, or other build tools, are not required for installing the library. Thus, it should be possible to include this library in a Google Cloud Functions by adding `blurhash-python` to `requirements.txt` file. One of the dependencies of this library, `Pillow`, may require `libjpeg` and other shared libraries in runtime for decoding images. Based on the documentation, these libraries are available on the Google Cloud Functions runtime.

In case this library does not work, there is also a version implemented in pure Python: https://github.com/halcy/blurhash-python. However, the pure Python version also requires `Pillow` and possibly other libraries, which yet again may need native libraries in runtime.

I hope this is a sufficient answer to your question. In case you have any further questions, I'll be happy to help.

**Comment by aytunch** [comment]
@lautat Thank you very much for the detailed answer. This helped me a lot and cleared lots of confusions about Python dependencies. I saw the pure Python implementation as well but I believe encoding with this library would be more performant since it uses C. I will try to mount this library on Google Cloud Functions now:) When I have more updates I will be leaving them here. Take care.
