### ISSUE TITLE
Can this be used without a file?

### ISSUE THREAD

**Issue by razzeee** [woltapp/blurhash-python#16]
Can this be used with data in an variable/ram or does it always need to be written to disk?

**Comment by lautat** [comment]
Hello @razzeee! Thanks for the good question. The `encode` method passes the first input parameter `image_file` to [`PIL.Image.open`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.open) method. According to the documentation, the parameter must be either a filename as string, a `pathlib.Path` object, or a file object which implements `read`, `seek`, and `tell` methods. The Python standard library includes [`io.BytesIO`](https://docs.python.org/3/library/io.html?highlight=io#io.BytesIO), which is a file-like in-memory buffer and has all these methods. For example, if you have a `bytes`-like object `data`, you could use it as follows:
```python
import io

import blurhash

data = ...  # a bytes-like object containing image data
buffer = io.BytesIO(data)
hash = blurhash.encode(buffer, x_components=4, y_components=3)
```
So the answer is yes, it can be used with data in memory without writing anything to disk or a temporary file.

Examples in the `README.md` file seem to only use a filename and a file object as a parameter. Thus, I think it could be updated to mention `io.BytesIO` so it is clear that the input doesn't have to be a file on disk.

**Comment by razzeee** [comment]
Thanks, I've ended up doing it like this https://github.com/flathub/backend/pull/105/files
