### ISSUE TITLE
Invalid Index to Scalar Variable

### ISSUE THREAD

**Issue by tanwarjigyasu** [woltapp/blurhash-python#20]
I was trying to convert a network image url to hash

```
image = Image.open(requests.get(url, stream=True).raw).resize((32, 32))
return encode(np.asarray(image), 4, 3, True)
```

I got an error saying `IndexError: invalid index to scalar variable.`

```
component = [0.0, 0.0, 0.0]
for y in range(int(height)):
    for x in range(int(width)):
    basis = norm_factor * math.cos(math.pi * float(i) * float(x) / width) * math.cos(math.pi * float(j) * float(y) / height)
    component[0] += basis * image_linear[y][x][0]
    component[1] += basis * image_linear[y][x][1]
    component[2] += basis * image_linear[y][x][2]
 
    component[0] /= (width * height)
    component[1] /= (width * height)
```

**Comment by lautat** [comment]
Hi! Looks like you're using the pure Python implementation [halcy/blurhash-python](https://github.com/halcy/blurhash-python), which is not maintained by us. Please send the issue to that repository. This project does not support passing images as numpy arrays to `encode` function.

If you'd like to try out this library instead, take a look at the [README](https://github.com/woltapp/blurhash-python/blob/master/README.md) for installation and usage instructions.
