### ISSUE TITLE
Decode support?

### ISSUE THREAD

**Issue by iomintz** [woltapp/blurhash-python#6]
Hi there. I'm interested in this code, and though I don't have any immediate plans to use it, I definitely might. I was wondering if there are plans to decode blur hashes to images of a certain width/height for display purposes? I could assist in adding the blurHash C code to this library if need be.

**Comment by lautat** [comment]
Hi! Thanks for showing interest in this library. Right now there are no plans to add decoding support to this library. All contributions are welcome. If you decide to implement it, you can open a pull request, and I'll try help you as much as possible to get it done. Note that there is another Python implementation, https://github.com/halcy/blurhash-python, which also has a decoder. It seems that we don't have a C decoder in https://github.com/woltapp/blurhash repository so you could also contribute there if you're interested in implementing a decoder in C.

**Comment by iomintz** [comment]
I tried writing it in C, but my C chops aren't great yet, so I'll give it another go in pure py and come back to this repo with a draft PR in C. How does that sound?

**Comment by lautat** [comment]
Sounds good! Don't worry too much about the C implementation. I should know enough C to help you get it to a decent shape once you have some implementation done.

**Comment by iomintz** [comment]
:relaxed: I'll at least try the C one anyway as a learning exercise. Any feedback on my shoddy C is valuable to me.

**Comment by iomintz** [comment]
Feel free to assign this to me within GitHub.

**Comment by Narasimha1997** [comment]
@iomintz @lautat 
Recently I built a decoder in C for Blurhash. I would like to assist you in adding this to the repo, so that others can benefit from it, or as @lautat mentioned, they can use another port which has python based decoder. 

@iomintz , please let me know if how I can assist you. 
Regards, 
Prasanna

**Comment by iomintz** [comment]
Is this your decoder? https://github.com/Narasimha1997/blurhash/tree/added-c-decoder/C/decoder

I'll take a look and try my hand at binding to it in Python

**Comment by Narasimha1997** [comment]
@iomintz , sure, otwrhwise let me know I will make a PR to this repo.

**Comment by iomintz** [comment]
@Narasimha1997 go ahead haha. at this point you seem more motivated than i do

**Comment by Narasimha1997** [comment]
@lautat , I've made a PR implementing the decoder in C (to the original Blurhash repo), please check that out. If you're okay with that, I can build the python wrapper and make a PR to this repo as well. 

Link to the PR : 
https://github.com/woltapp/blurhash/pull/94

Thanks and Regards.

**Comment by lautat** [comment]
Hi @Narasimha1997! Thanks for the pull request. I can have a look at it as well, but I'll try to find someone else to review it. Of course, a pull request which adds a Python wrapper for the C decoder is welcome. Let me know if you have any questions or need help with the Python wrapper.

**Comment by Narasimha1997** [comment]
Sure, will add the python wrapper soon. 👍

**Comment by Narasimha1997** [comment]
#7 checkout this PR.

**Comment by lautat** [comment]
Resolved by #7
